kind: pipeline
name: deploy portfolio

steps:
- name: build and deploy portfolio
  image: docker
  commands:
  - docker-compose -p portfolio up --build -d
  volumes:
  - name: docker_sock
    path: /var/run/docker.sock

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

when:
  branch:
  - main
  event:
  - push
